---
title: "Commands"
output:
  github_document:
    df_print: tibble
editor_options: 
  chunk_output_type: inline
---


Right now I'm using this as scrap.
```{r global_options, include=FALSE}
source(here::here("common.R"))
library(tidyverse)
library(knitr)

colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color, 
      x)
  } else x
}


```







```{r,message=FALSE}

git_color <- function(text,color) {
  str_glue("<span style=\"color: {color};\">{text}</span>")
}



join_show <- function(x,y,by=NULL) {
  if (is.null(by)) {
    by <- intersect(names(x),names(y))
  }
  if (is.null(names(by))) {
    by.x <- by
    by.y <- by
  } else {
    by.x <- names(by)
    by.y <- by
  }
  x2 <- x %>% mutate(across(-c(!!!syms(by.x)),~git_color(.,"red"))) %>% rename_with(~git_color(.,"red"),.cols=-c(!!!syms(by.x)))
  y2 <- y %>% mutate(across(-c(!!!syms(by.y)),~git_color(.,"blue"))) %>% rename_with(~git_color(.,"blue"),.cols=-c(!!!syms(by.y)))
  left <- left_join(x2,y2,by=by)
  inner <- inner_join(x2,y2,by=by)
  right <- right_join(x2,y2,by=by)
  full <- full_join(x2,y2,by=by)
  list(x=x2,y=y2,left=left,right=right,inner=inner,full=full)
}


join_show_rows <- function(x,y,by=NULL) {
  if (is.null(by)) {
    by <- intersect(names(x),names(y))
  }
  if (is.null(names(by))) {
    by.x <- by
    by.y <- by
  } else {
    by.x <- names(by)
    by.y <- by
  }
  values <- full_join(x,y,by=by) %>% select(!!!syms(by.x)) %>% distinct() %>% mutate(.color=scales::col_factor("RdYlBu",domain=NULL)(row_number()))
  x2 <- x %>% left_join(values,by=by.x) %>% mutate(across(-.color,~map2_chr(.,.color,~git_color(.x,.y)))) %>% select(-.color)
  y2 <- y %>% left_join(values,by=setNames(by.x,by.y)) %>% mutate(across(-.color,~map2_chr(.,.color,~git_color(.x,.y)))) %>% select(-.color)

  left <- left_join(x2,y2,by=by)
  inner <- inner_join(x2,y2,by=by)
  right <- right_join(x2,y2,by=by)
  full <- full_join(x2,y2,by=by)
  list(x=x2,y=y2,left=left,right=right,inner=inner,full=full)
}

```



```{r}
library(yingtools2)
t <- join_show_rows(band_members,band_instruments)



knitr::kables(list(
  kable(t$x,caption="x"),
  kable(t$y,caption="y")
))

kable(t$left,caption="left_join")

kable(t$right,caption="right_join")

kable(t$inner,caption="inner_join")

kable(t$full,caption="full_join")



```



```{r}
#survival 



library(survival)
library(survminer)
## kaplan meier
fit <- survfit(Surv(cdiff_day,cdiff)~randomization_arm,data=pt.surv)
plot(fit)
## kaplan meier (survminer)
fit <- survfit(Surv(cdiff_day,cdiff)~randomization_arm,data=pt.surv)
ggsurvplot(fit,conf.int=FALSE,censor=FALSE,pval=TRUE)
## kaplan meier #2 (old way)
dd <- pt.surv %>% mutate(tstart=0)
ggplot() + geom_kaplanmeier("cdiff","randomization_arm",data=dd,logrank=TRUE)

## kaplan meier #3 (manual #1)
fit <- survfit(Surv(cdiff_day,cdiff)~randomization_arm,data=pt.surv)
survdata <- survminer::surv_summary(fit) %>% survminer:::.connect2origin()
ggplot(survdata,aes(x=time,y=surv,color=strata)) + geom_step()

## kaplan meier #4 (manual #2)
fit <- survfit(Surv(cdiff_day,cdiff)~randomization_arm,data=pt.surv)
survdata <- tibble(surv=fit$surv,time=fit$time,strata=rep(names(fit$strata),fit$strata),
                   n.risk=fit$n.risk,n.event=fit$n.event,n.censor=fit$n.censor,std.err=fit$std.err,
                   lower=fit$lower,upper=fit$upper) %>%
  group_by(strata) %>% group_modify(~{
    origin <- .x %>% slice(1) %>%
      mutate(across(c(time,n.censor,std.err,n.event),~0),
             across(c(surv,upper,lower),~1))
    bind_rows(origin,.x)
  })
sd <- survdiff(Surv(cdiff_day,cdiff)~randomization_arm,data=pt.surv)
logrank.pval <- 1 - pchisq(sd$chisq, length(sd$n) - 1)

ggplot(survdata,aes(x=time,y=surv,color=strata)) + geom_step()




fit <- survfit(Surv(cdiff_day,cdiff)~randomization_arm,data=pt.surv)
g1=ggsurvplot(fit,conf.int=FALSE,censor=FALSE,pval=TRUE)
## kaplan meier #2 (old way)
dd <- pt.surv %>% mutate(tstart=0)
g2=ggplot() + geom_kaplanmeier("cdiff","randomization_arm",data=dd,logrank=TRUE)

## kaplan meier #3 (manual #1)
fit <- survfit(Surv(cdiff_day,cdiff)~randomization_arm,data=pt.surv)
survdata <- survminer::surv_summary(fit) %>% survminer:::.connect2origin()
g3=ggplot(survdata,aes(x=time,y=surv,color=strata)) + geom_step()

## kaplan meier #4 (manual #2)
fit <- survfit(Surv(cdiff_day,cdiff)~randomization_arm,data=pt.surv)
survdata <- tibble(surv=fit$surv,time=fit$time,strata=rep(names(fit$strata),fit$strata),
                   n.risk=fit$n.risk,n.event=fit$n.event,n.censor=fit$n.censor,std.err=fit$std.err,
                   lower=fit$lower,upper=fit$upper) %>%
  group_by(strata) %>% group_modify(~{
    origin <- .x %>% slice(1) %>%
      mutate(across(c(time,n.censor,std.err,n.event),~0),
             across(c(surv,upper,lower),~1))
    bind_rows(origin,.x)
  })
g4=ggplot(survdata,aes(x=time,y=surv,color=strata)) + geom_step()



## CIFs
fit <- cuminc(pt.surv$bmtdead_day,pt.surv$bmtdead,group=pt.surv$randomization_arm)

fg.pval <- fit$Tests["1","pv"]
plot(fit)
## CIFs #2
fit <- cuminc(pt.surv$bmtdead_day,pt.surv$bmtdead,group=pt.surv$randomization_arm)
ggcompetingrisks(fit,multiple_panels=FALSE)

## CIFs #3 (manual)
fit <- cuminc(pt.surv$bmtdead_day,pt.surv$bmtdead,group=pt.surv$randomization_arm)
survdata <- fit %>% list_modify("Tests"=NULL) %>%
  map_dfr(~.,.id="id") %>% filter(grepl(" 1$",id)) %>% 
  mutate(id=sub(" 1$","",id))
fg.pval <- fit$Tests["1","pv"]
ggplot(survdata,aes(x=time,y=est,color=id)) +
  geom_step()  +
  annotate("text",x=100,y=0.5,label=str_glue("Fine-Gray P={scales::pvalue(fg.pval)}"))






```




```{r}

t <- join_show(band_members,band_instruments)
# t <- join_show(cid.patients,cid.cdiff)

knitr::kables(list(
  kable(t$x,caption="x"),
  kable(t$y,caption="y")
))

kable(t$left,caption="left_join")

kable(t$right,caption="right_join")

kable(t$inner,caption="inner_join")

kable(t$full,caption="full_join")



```
